apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic-kodung-front
  labels:
    app: mk-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mk-front
  template:
    metadata:
      labels:
        app: mk-front
    spec:
      containers:
        - name: mk-front
          image: front
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: magic-kodung-front-nodeport
spec:
  type: NodePort
  selector:
    app: mk-front
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31007
